CREATE TABLE SALESMAN (SNO INT, 
					   S_NAME varchar (30), 
					   START_YEAR INT, 
					   DEPTNO varchar (10));
					   
CREATE TABLE TRIP (TNO INTEGER, FROM_CITY varchar (20), 
	  TO_CITY varchar (20), 
	  DEPARTURE_DATE DATE, RETURN DATE, SNO INT, DNO INT);
	  
CREATE TABLE DEPT (DEPTNO varchar (10) PRIMARY KEY, DEPT_NAME varchar(20));

CREATE TABLE EXPENSE (EID INT PRIMARY KEY, AMOUNT INT, TNO INT);

DROP TABLE EXPENSE;


INSERT INTO SALESMAN VALUES (2, 'Sumit', 2021, 'IT');

INSERT INTO TRIP VALUES (2, 'DELHI', 'MUMBAI', '2022-05-02', '2022-05-09',2);

INSERT INTO DEPT VALUES (2, 'FMCG');

INSERT INTO EXPENSE VALUES (2, 15000, 2);

UPDATE EXPENSE SET AMOUNT = 15000 WHERE EID=2;

SELECT SALESMAN.SNO, S_NAME FROM SALESMAN INNER JOIN TRIP ON 
SALESMAN.SNO = TRIP.SNO WHERE TO_CITY = 'Calcutta';

SELECT * FROM TRIP INNER JOIN EXPENSE ON TRIP.TNO = EXPENSE.TNO WHERE AMOUNT>10000;

delete from trip where tno = (select tno from expense where amount>15000);




ALTER TABLE TRIP ADD COLUMN dno INT;
UPDATE TRIP SET dno=1;


